### ISSUE TITLE
Use generics for TypeScript definitions to specify outputs

### ISSUE THREAD

**Issue by disambiguator** [Zaplib/zaplib#129]
`callRust` is currently typed such that it returns ZapParams, but that requires us to cast when we should know what the return value is. What if instead:
```ts
// currently
const val = zaplib.callRust("foo");
const foo = val[0] as Uint8Array;
const bar = val[1] as string;

// after
const [foo, bar] = zaplib.callRust<[Uint8Array, string]>("foo");
```

**Comment by janpaul123** [comment]
Yeah I like that a lot as an incremental improvement! I think this interface will end up super similar to our `rpc.send` once we implement Typescript definition generation (part of https://github.com/Zaplib/zaplib/issues/99), and this change feels on that path.
