### ISSUE TITLE
Better Rust error handling

### ISSUE THREAD

**Issue by janpaul123** [Zaplib/zaplib#13]
- [x] Panics should raise an error to user code so it can deal with it
  - [x] Console shouldn't get spammed with errors
  - [ ] Panics should be catchable to user code from `handle` and `draw` calls.

**Comment by janpaul123** [comment]
@disambiguator Small bug (I think) that I came across in the current implementation: panics now seem to be completely silenced when they don't originate from the JS side. We just set `wasmOnline` to 0, but the error message in that case gets lost.

Should we still call print to the console during `_throwError` for now? Or maybe we can solve this when you add the JS callback for errors — by default that callback can print to the console but you can override it to do other things?

**Comment by disambiguator** [comment]
@janpaul123 Can you explain this comment a bit more? I don't really get what you mean by silenced. I added a `panic!` in a `handle` function, and I in fact do see it in the JS console.

For example: in the test suite handle function if I do...
```rust
        match event {
            Event::Signal(_) => {
                panic!("Ahhh!");
            }
            _ => {}
        }
```

and then press "Send signal from worker":
I see:
```
Uncaught RustPanic: panicked at 'Ahhh!', zaplib/test_suite/src/main.rs:41:17
    at _throwError ([module]:353:19)
    ...
```

**Comment by janpaul123** [comment]
@disambiguator Ahh thanks for checking! I think I got misled by the behavior in #30, which didn't in fact throw an error but just caused `wasmOnline` to be set to 0. All good then! 🎉
