### ISSUE TITLE
Include unminified files in package + document source maps in Webpack

### ISSUE THREAD

**Issue by disambiguator** [Zaplib/zaplib#83]
Including full JS source / sourcemaps will make local development much easier when running into something confusing in the framework.

**Comment by janpaul123** [comment]
We do supply source maps, but it would indeed be good to ship both production and development versions. React uses "*.development.js" and "*.production.js" suffixes for this.

**Comment by janpaul123** [comment]
Re source maps: we should document how to use Zaplib with Webpack; especially ingesting source maps: https://webpack.js.org/loaders/source-map-loader/

**Comment by disambiguator** [comment]
@janpaul123 is this done? I'm not sure if we need more sourcemap work.

**Comment by janpaul123** [comment]
Ahh good point, I forgot about that. Maybe we should just briefly mention the source-map-loader Webpack plugin for if you want Zaplib source maps in production? E.g. in "Webpack Integration"? (Even though we haven't actually tried it 😬 )

Either way, happy to close this when you're happy!

**Comment by disambiguator** [comment]
i think its fine, we package them and i think that's enough 🤷🏽  I'll close it.
